### ISSUE TITLE
Tag node-test-image as 'latest'

### ISSUE THREAD

**Issue by petersutter** [gardener/node-test-image#3]
tag node-test-image image as latest, so that we can reference it directly [here](https://github.com/gardener/dashboard/blob/master/.ci/pipeline_definitions#L21) so that we do not have to update this file after every build of this component
 

> You may now tag images published by our Concourse as 'latest' *in addition* to the effective version by setting the `tag_as_latest` attribute to `true`. Example:

```
...
  traits:
    publish:
      dockerimages:
        some-image-name:
          registry: gcr-readwrite
          image: eu.gcr.io/foo/bar
          dockerfile: Dockerfile
          tag_as_latest: true
...
```
